package com.example.data

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "qr_history")
data class QrItem(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val content: String,
    val type: String, // "TEXT", "URL", "WIFI", "CONTACT", "SMS", "PHONE"
    val isGenerated: Boolean, // true if generated by user, false if scanned
    val timestamp: Long = System.currentTimeMillis()
)
